### ISSUE TITLE
不好意思，但是我想问你件事

### ISSUE THREAD

**Issue by Irwin1985** [bigwhite/experiments#6]
你好 Tony,

I just want to ask you if GoLang is a good choice for making a programming language.

对了，我是西班牙人，但是我很喜欢中文！

谢谢你！

**Comment by bigwhite** [comment]
go已经实现自举，也就是说go的编译器就是自己实现的。因此用go实现编译器是不错的选择。可以参考一本书 https://compilerbook.com/ 

go has implemented bootstrap itself, which means that go's compiler is implemented in go. So it is good to implement a  compiler with go. You can refer to a book https://compilerbook.com/
